<a href="https://colab.research.google.com/github/Aditya-Walia1/ML-Assignments/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Assignment 1

In [ ]:
import numpy as np


In [ ]:
arr=([1,2,3,4,5,6,7,8])
arr=np.array(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#Question 1 (a)
arr1=arr[::-1]
arr1

array([8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
arr2=np.flip(arr)
arr2

array([8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
#Question 1 b
array1 = np.array([[1,2,3],[4,5,6],[3,4,5]])
flatten1=array1.flatten()
print(flatten1)

array2=array1.ravel()
print(array2)

[1 2 3 4 5 6 3 4 5]
[1 2 3 4 5 6 3 4 5]


In [ ]:
#Question 1 c
arr1=np.array([[1,2,3],[3,4,5],[6,7,8]])
arr2=np.array([[3,4,5],[6,7,8],[9,10,11]])

comparison=np.array_equal(arr1,arr2)
print(comparison)

False


In [ ]:
arrays_equal = np.array_equal(arr1, arr2)
arrays_equal

False

In [ ]:
#Question 1 d
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

def most_frequent(array):
    unique,counts = np.unique(array,return_counts=True)
    index = np.argmax(counts)
    return unique[index]

print(most_frequent(x))
print(most_frequent(y))



In [ ]:
#Question 1  e
gfg=np.matrix('[4,1,9 ; 12,3,1 ; 4,5,6]')
gfg

sum_all=gfg.sum()
print(sum_all)

sum_row=gfg.sum(axis=1)
print(sum_row)

sum_col=gfg.sum(axis=0)
print(sum_col)

In [ ]:
#Question 1 f
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

sum_diagnol = np.trace(n_array)
print(sum_diagnol)

eigen_values,eigen_vectors=np.linalg.eig(n_array)
print(eigen_values)
print(eigen_vectors)

w, v = np.linalg.eig(n_array)
print(w)
print(v)

determinant=np.linalg.det(n_array)
print(determinant)


176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
137180.0000000001


In [ ]:
#Question 1  g
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

# Matrix multiplication
product1 = np.dot(p1, q1)
product2 = np.dot(p2, q2)

# Covariance
covariance1 = np.cov(p1, rowvar=False)
covariance2 = np.cov(p2, rowvar=False)

print(product1)
print(product2)
print(covariance1)
print(covariance2)


In [ ]:
#Question 1 h
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner product
inner_product = np.inner(x, y)

# Outer product
outer_product = np.outer(x, y)



print(inner_product)
print(outer_product)



[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [ ]:
#Question 2 a
array = np.array([[1, -2, 3], [-4, 5, -6]])

absolute_array = np.abs(array)
print(absolute_array)


[[1 2 3]
 [4 5 6]]


In [ ]:
flattened_array = array.flatten()

percentiles_flattened = np.percentile(flattened_array, [25, 50, 75])
percentiles_column = np.percentile(array, [25, 50, 75], axis=0)
percentiles_row = np.percentile(array, [25, 50, 75], axis=1)

print(percentiles_flattened)
print(percentiles_column)
print(percentiles_row)


[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [ ]:
mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_flattened = np.std(flattened_array)

mean_column = np.mean(array, axis=0)
median_column = np.median(array, axis=0)
std_column = np.std(array, axis=0)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print(mean_flattened, median_flattened, std_flattened)
print(mean_column, median_column, std_column)
print(mean_row, median_row, std_row)


-0.5 -0.5 3.8622100754188224
[-1.5  1.5 -1.5] [-1.5  1.5 -1.5] [2.5 3.5 4.5]
[ 0.66666667 -1.66666667] [ 1. -4.] [2.05480467 4.78423336]


In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_values = np.floor(a)
ceil_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)

print(floor_values)
print(ceil_values)
print(truncated_values)
print(rounded_values)


[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

# Sorted array
sorted_array = np.sort(array)

# Indices of sorted array
sorted_indices = np.argsort(array)

# 4 smallest elements
four_smallest = np.sort(array)[:4]

# 5 largest elements
five_largest = np.sort(array)[-5:]

print("Sorted array:", sorted_array)
print("Indices of sorted array:", sorted_indices)
print("4 smallest elements:", four_smallest)
print("5 largest elements:", five_largest)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [ ]:
#Question 4
import numpy as np
from PIL import Image

def img_to_array(path):
    img = Image.open(path)
    img_array = np.array(img)
    if img_array.ndim == 3:  # RGB image
        np.savetxt("image_rgb.txt", img_array.reshape(-1, img_array.shape[2]), fmt='%d')
    else:  # Grayscale image
        np.savetxt("image_gray.txt", img_array, fmt='%d')
    return img_array

# Example usage
path = 'path_to_image.jpg'
img_array = img_to_array(path)


In [ ]:
# Loading RGB image text file
loaded_rgb = np.loadtxt("image_rgb.txt").reshape(-1, 3)

# Loading grayscale image text file
loaded_gray = np.loadtxt("image_gray.txt")

print(loaded_rgb)
print(loaded_gray)
